[package]
name = "oxc_parallel_test"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = ["/src", "build.rs"]
keywords.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "lib"]
test = false
doctest = false

[dependencies]
bpaf = { workspace = true, features = ["autocomplete", "bright-color", "derive"] }
napi = { workspace = true, features = ["async"] }
napi-derive = { workspace = true }
rayon = { workspace = true }
simdutf8 = { workspace = true }

oxc_allocator = { workspace = true, features = ["fixed_size"] }
oxc_parser = { workspace = true }
oxc_span = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }

[features]
default = []
